### ISSUE TITLE
exception on running TJBatchExtractor for first time

### ISSUE THREAD

**Issue by Snikket** [mille856/CMU_memex#1]
Hey I created a sample text file to try out the TJBatchExtractor but every time I try to run it I'm getting a number of exceptions pasted below. Any suggestions?

I am using Java 1.8 and I'm running the program with one thread and input file called "zeta.txt":
java -classpath '.:dependencies/*' TJBatchExtractor 1 ~/zeta.txt

Exception in thread "main" gate.persist.PersistenceException: com.thoughtworks.xstream.converters.ConversionException: -1 : -1
---- Debugging information ----
message             : -1
cause-exception     : java.lang.ArrayIndexOutOfBoundsException
cause-message       : -1
class               : gate.util.persistence.SerialAnalyserControllerPersistence
required-type       : gate.util.persistence.SerialAnalyserControllerPersistence
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /application
line number         : 20
## version             : null

```
at gate.util.persistence.PersistenceManager.loadObjectFromUrl(PersistenceManager.java:937)
at gate.util.persistence.PersistenceManager.loadObjectFromFile(PersistenceManager.java:824)
at TJBatchExtractor.main(TJBatchExtractor.java:93)
```

Caused by: com.thoughtworks.xstream.converters.ConversionException: -1 : -1
---- Debugging information ----
message             : -1
cause-exception     : java.lang.ArrayIndexOutOfBoundsException
cause-message       : -1
class               : gate.util.persistence.SerialAnalyserControllerPersistence
required-type       : gate.util.persistence.SerialAnalyserControllerPersistence
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /application
line number         : 20
## version             : null

```
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1058)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1030)
at com.thoughtworks.xstream.XStream$2.readFromStream(XStream.java:1723)
at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:104)
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:365)
at gate.util.persistence.PersistenceManager.loadObjectFromUrl(PersistenceManager.java:913)
... 2 more
```

Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at com.thoughtworks.xstream.core.util.OrderRetainingMap.entrySet(OrderRetainingMap.java:77)
    at java.util.HashMap.putMapEntries(HashMap.java:511)
    at java.util.HashMap.putAll(HashMap.java:784)
    at com.thoughtworks.xstream.core.util.OrderRetainingMap.<init>(OrderRetainingMap.java:36)
    at com.thoughtworks.xstream.converters.reflection.FieldDictionary.buildMap(FieldDictionary.java:135)
    at com.thoughtworks.xstream.converters.reflection.FieldDictionary.fieldOrNull(FieldDictionary.java:113)
    at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.fieldDefinedInClass(PureJavaReflectionProvider.java:160)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:254)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:234)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
    ... 13 more
  Caused by:
com.thoughtworks.xstream.converters.ConversionException: -1 : -1
---- Debugging information ----
message             : -1
cause-exception     : java.lang.ArrayIndexOutOfBoundsException
cause-message       : -1
class               : gate.util.persistence.SerialAnalyserControllerPersistence
required-type       : gate.util.persistence.SerialAnalyserControllerPersistence
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /application
line number         : 20
## version             : null

```
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1058)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1030)
at com.thoughtworks.xstream.XStream$2.readFromStream(XStream.java:1723)
at com.thoughtworks.xstream.core.util.CustomObjectInputStream.readObjectOverride(CustomObjectInputStream.java:104)
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:365)
at gate.util.persistence.PersistenceManager.loadObjectFromUrl(PersistenceManager.java:913)
at gate.util.persistence.PersistenceManager.loadObjectFromFile(PersistenceManager.java:824)
at TJBatchExtractor.main(TJBatchExtractor.java:93)
```

Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at com.thoughtworks.xstream.core.util.OrderRetainingMap.entrySet(OrderRetainingMap.java:77)
    at java.util.HashMap.putMapEntries(HashMap.java:511)
    at java.util.HashMap.putAll(HashMap.java:784)
    at com.thoughtworks.xstream.core.util.OrderRetainingMap.<init>(OrderRetainingMap.java:36)
    at com.thoughtworks.xstream.converters.reflection.FieldDictionary.buildMap(FieldDictionary.java:135)
    at com.thoughtworks.xstream.converters.reflection.FieldDictionary.fieldOrNull(FieldDictionary.java:113)
    at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.fieldDefinedInClass(PureJavaReflectionProvider.java:160)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:254)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:234)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
    ... 13 more

**Comment by swints** [comment]
Did you ever resolve this issue? I am getting the same problem.

**Comment by mille856** [comment]
I think it's a java version issue, I haven't done anything about it.

-------- Original message --------

**Comment by swints** [comment]
Which Java version is the MEMEX code designed to be compatible with?

**Comment by mille856** [comment]
I used openjdk 1.7.0_95

-------- Original message --------

**Comment by timg456789** [comment]
I was able to get the project running using the latest version of java available from the Oracle archive page [jdk1.7.0_80](http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html)
